version: '3.7'

services:
  database:
    container_name: host
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=rentex
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=rentx
    ports:
      - 5000:5432
    volumes:
      - pgdata:/data/postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - host

  database_test:
    container_name: host-test
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=rentex
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=rentx_test
    ports:
      - 5500:5432
    volumes:
      - pgdata:/data/postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - host
  # web:
  #   image: node
  #   build: .
  #   restart: always
  #   volumes:
  #     - .:/app/src
  #   ports:
  #     - 3333:3333
  #   depends_on:
  #     database:
  #       condition: service_healthy
  #   networks:
  #     - host

volumes:
  pgdata:
    driver: local
networks:
  host:
    driver: bridge
